export const CMR_CATEGORY_NAMES: { [key: string]: string } = {
  'AIDS': 'AIDS/HIV',
  'ALCOHOL': 'Alcohol abuse',
  'ANEMDEF': 'Deficiency anemia',
  'AUTOIMMUNE': 'Autoimmune conditions',
  'BLDLOSS': 'Blood loss anemia',
  'CANCER_LEUK': 'Leukemia',
  'CANCER_LYMPH': 'Lymphoma',
  'CANCER_METS': 'Metastatic cancer',
  'CANCER_NSITU': 'Cancer in situ',
  'CANCER_SOLID': 'Solid tumor without metastasis',
  'CBVD_POA': 'Cerebrovascular disease (POA)',
  'CBVD_SQLA': 'Cerebrovascular disease (sequelae)',
  'COAG': 'Coagulopathy',
  'DEMENTIA': 'Dementia',
  'DEPRESS': 'Depression',
  'DIAB_CX': 'Diabetes with complications',
  'DIAB_UNCX': 'Diabetes without complications',
  'DRUG_ABUSE': 'Drug abuse',
  'HF': 'Heart failure',
  'HTN_CX': 'Hypertension with complications',
  'HTN_UNCX': 'Hypertension without complications',
  'LIVER_MLD': 'Liver disease (mild)',
  'LIVER_SEV': 'Liver disease (severe)',
  'LUNG_CHRONIC': 'Chronic pulmonary disease',
  'NEURO_MOVT': 'Neurological movement disorders',
  'NEURO_OTH': 'Other neurological disorders',
  'NEURO_SEIZ': 'Seizures and epilepsy',
  'OBESE': 'Obesity',
  'PARALYSIS': 'Paralysis',
  'PERIVASC': 'Peripheral vascular disease',
  'PSYCHOSES': 'Psychoses',
  'PULMCIRC': 'Pulmonary circulation disorders',
  'RENLFL_MOD': 'Renal failure (moderate)',
  'RENLFL_SEV': 'Renal failure (severe)',
  'THYROID_HYPO': 'Hypothyroidism',
  'THYROID_OTH': 'Other thyroid disorders',
  'ULCER_PEPTIC': 'Peptic ulcer disease',
  'VALVE': 'Valvular disease',
  'WGHTLOSS': 'Weight loss'
};
